---
rule_files:
- /tmp/manifests/prometheus_alerts.yaml
- /tmp/manifests/prometheus_rules.yaml

evaluation_interval: 1m

tests:
- interval: 1m
  input_series:
  - series: 'sealed_secrets_controller_unseal_errors_total{status="update"}'
    values: '0+0x20'
  - series: 'sealed_secrets_controller_unseal_errors_total{status="update"}'
    values: '0+0x5 1+1x20'
  - series: 'sealed_secrets_controller_unseal_errors_total{status="unseal"}'
    values: '0+0x20'
  - series: 'sealed_secrets_controller_unseal_errors_total{status="unseal"}'
    values: '0+0x5 1+1x20'
  alert_rule_test:
  - eval_time: 4m
    alertname: SealedSecretsUnsealErrorRateHigh
  - eval_time: 6m
    alertname: SealedSecretsUnsealErrorRateHigh
    exp_alerts:
    - exp_labels:
        severity: warning
      exp_annotations:
        message: 'High rate of errors unsealing Sealed Secrets'
        runbook: 'https://github.com/bitnami-labs/sealed-secrets'
