annotations:
  category: DeveloperTools
apiVersion: v2
appVersion: v0.17.4
description: Helm chart for the sealed-secrets controller.
home: https://github.com/bitnami-labs/sealed-secrets
icon: https://bitnami.com/assets/stacks/sealed-secrets/img/sealed-secrets-stack-220x234.png
keywords:
  - secrets
  - sealed-secrets
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: containers@bitnami.com
    name: Bitnami
  - name: mkmik
    email: mmikulicic@gmail.com
name: sealed-secrets
type: application
version: 2.1.5
